version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://user:password@postgres-db:5432/todo_db
    depends_on:
      - postgres-db
    networks:
      - backend_network
    volumes:
      - .:/app
      - ./logs:/usr/src/app/logs
    command: npm run dev

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network

volumes:
  pgdata:

networks:
  backend_network: